wandb_version: 1

learning-rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 4
context_len:
  desc: null
  value: 10
eval_interval:
  desc: null
  value: 1000
n_embed:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1715871460
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
